### ISSUE TITLE
Repository Path Change

### ISSUE THREAD

**Issue by bajaloreto** [PnRSolutions/bookerei-public#4]
Hi there!, First thanks and congrats for your app! 

I tried to change the repository path to a folder in an external HDD, (I did it before adding any ebooks). But it does not remain as default in the settings, once I close the app and then turn it on again, the path re-establishes itself to the original. 

Perhaps I am doing it wrong, and the app does not support external HDD?

**Comment by d3lboy** [comment]
Hi,

It should remember the path. The only thing is that the external HDD must be connected before you start the app. Otherwise, it tries to read that external path, and if no success, it reverts to the default one.
Are you using Windows or MacOS?

I will investigate.

**Comment by d3lboy** [comment]
@bajaloreto 

Due to MacOS restrictions, accessing folders outside the sandbox requires user action. As a result, the app reverts the repository path to the default one when permissions are removed after the app is closed.

To resolve this, the latest release (v1.6.0) includes a “Select Folder” dialog. Your new repository is set as default, just click “Open” to proceed. This should ensure everything works as expected.

Please update the app and check it.
