### ISSUE TITLE
Highlights aren't saving.

### ISSUE THREAD

**Issue by RackDaddy** [PnRSolutions/bookerei-public#5]
I just installed v1.70.  I can make multiple highlights (it shows as highlighted inline), but they don't appear in the notes and highlights section.  When I close the book and return, the highlights are gone.

**Comment by d3lboy** [comment]
Thank you for pointing this out. It appears to be a bug, and I will investigate and resolve it promptly.

**Comment by d3lboy** [comment]
The bug-fix is now included in version 1.7.1.

**Comment by RackDaddy** [comment]
I installed 1.7.1 but noticed a few things.  The good news is that highlights are maintained.  Thanks!

1)  After upgrading to 1.7.1 and opening Bookerei, a popup appears stating that 1.7.0 is available and asks me if I want to upgrade.  After a few open/closes it goes away, so not a huge deal.

2)  For the icons on top when reading a book, when hovering over the left two icons the tooltip is the same, "Bookmarks and notes".  I believe the second icon tooltip should be "Add a note".

3)  Adding a note is great, and I like how I can jump to that place in the document, but there isn't a little note icon that appears in the text, so there is no frame of reference of what I've written a note about.

**Comment by d3lboy** [comment]
Thanks a lot for your feedback! It really helps us improve the software.

1. I forgot to update the latest version online. It’s fixed now.

2. This will be sorted out in the next release.

3. To link notes with specific book locations, use bookmarks. Adding notes directly doesn’t save the location because you can add notes from the book details without opening the book. Anyway, it might be a good idea to make notes connect to the page if you’re adding them while reading. I will put it in a backlog.
